my_project/Enhancing Personal Style/routes/main.py
import pandas as pd
from flask import Blueprint, render_template, request, g, redirect, url_for, jsonify
from flask_wtf.csrf import generate_csrf
from utils.prediction import predict_body_shape
from utils.database import get_db, close_db
# routes/main.py

main_bp = Blueprint('main', __name__)


@main_bp.before_app_request
def before_request():
    g.db = get_db()


@main_bp.teardown_app_request
def teardown_request(exception):
    close_db()


@main_bp.route('/view_database', methods=['GET'])
def view_database():
    query = "SELECT * FROM store_product"
    dataframe_store_product = pd.read_sql_query(query, g.db)
    json_data = dataframe_store_product.to_json(orient='records')
    return json_data


@main_bp.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        shape, gender, skin_tone = handle_form_request(request.form)
        return redirect(url_for('recommendations.recommend', shape=shape, gender=gender, skin_tone=skin_tone))
    return render_template('index.html', csrf_token=generate_csrf())


@main_bp.route('/predict_shape', methods=['POST'])
def predict_shape():
    data = request.json
    gender = data.get('gender')
    chest = data.get('chest')
    waist = data.get('waist')
    high = data.get('high')
    hip = data.get('hip')
    predicted_shape = predict_body_shape(gender, chest, waist, high, hip)
    return jsonify({'predicted_shape': predicted_shape})


def handle_form_request(request_form):
    shape = request_form.get('shape')
    gender = request_form.get('gender')
    skin_tone = request_form.get('skin_tone')
    if shape == "Predict":
        chest = float(request_form.get('Chest'))
        waist = float(request_form.get('Waist'))
        high = float(request_form.get('High'))
        hip = float(request_form.get('Hip'))
        shape = predict_body_shape(gender, chest, waist, high, hip)
    return shape, gender, skin_tone

my_project/Enhancing Personal Style/routes/recommendations.py
import pandas as pd
from flask import Blueprint, render_template, request, g, session, redirect, url_for
from flask_wtf import FlaskForm
from wtforms.fields.simple import HiddenField, SubmitField
from wtforms.validators import DataRequired
from utils.collaborative_filtering import collaborative_filtering
from utils.content_based_filtering import select_random_cbf_products, random_recommendations
from utils.recommend_init import process_recommendations, group_recommendations_by_subcategory, \
    fetch_recommendation_data
# /routes/recommendations.py
recommendations_bp = Blueprint('recommendations', __name__)


class LikeForm(FlaskForm):
    product_id = HiddenField('Product ID', validators=[DataRequired()])
    submit = SubmitField('Submit')


@recommendations_bp.route('/recommend', methods=['GET'])
def recommend():
    if 'user_id' not in session:
        return redirect(url_for('user.login'))
    user_id = session.get('user_id')
    db = g.db
    shape, gender, skin_tone, dataframe, cbf_recommendations = fetch_recommendation_data(user_id, db, request.args)
    user_likes_query = "SELECT item_id FROM user_likes WHERE user_id = ?"
    user_likes = db.execute(user_likes_query, (user_id,)).fetchall()
    liked_products = [item[0] for item in user_likes]
    user_likes_query_all = "SELECT user_id, item_id FROM user_likes"
    user_likes_all = db.execute(user_likes_query_all).fetchall()
    user_likes_df = pd.DataFrame(user_likes_all, columns=['user_id', 'item_id'])
    cf_recommendations = collaborative_filtering(user_likes_df)
    final_recommendations = process_recommendations(cbf_recommendations, cf_recommendations, dataframe, user_likes_df,
                                                    skin_tone, gender)
    grouped_recommendations = group_recommendations_by_subcategory(final_recommendations)
    form = LikeForm()
    return render_template('recommendation.html', products=grouped_recommendations, user_shape=shape,
                           user_gender=gender, user_skin_tone=skin_tone, liked_products=liked_products, form=form)


@recommendations_bp.route('/test_recommend', methods=['GET'])
def test_recommend():
    if 'user_id' not in session:
        return redirect(url_for('user.login'))
    user_id = session.get('user_id')
    db = g.db
    shape, gender, skin_tone, dataframe, cbf_recommendations = fetch_recommendation_data(user_id, db, request.args)
    cbf_df = select_random_cbf_products(cbf_recommendations, dataframe)
    cbf_df['filtering'] = 'content-based'
    random_df = random_recommendations(db, gender)
    random_df['filtering'] = 'random'
    test_recommendations = pd.concat([cbf_df, random_df])
    test_recommendations = test_recommendations.sample(frac=1)
    test_recommendations_json = test_recommendations.to_json(orient='records')
    return render_template('user_testing_recommendation.html', products=test_recommendations_json,
                           user_shape=shape, user_gender=gender, user_skin_tone=skin_tone, user_id=user_id)

my_project/Enhancing Personal Style/routes/test.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_wtf.csrf import generate_csrf
from routes.main import handle_form_request
# routes/test.py
test_bp = Blueprint('test', __name__)


@test_bp.route('/test', methods=['GET', 'POST'])
def test():
    if request.method == 'POST':
        shape, gender, skin_tone = handle_form_request(request.form)
        return redirect(url_for('recommendations.test_recommend', shape=shape, gender=gender, skin_tone=skin_tone))
    return render_template('user_testing.html', csrf_token=generate_csrf())

my_project/Enhancing Personal Style/routes/user.py
from flask import Blueprint, render_template, request, redirect, url_for, session, g, jsonify
from flask_wtf import FlaskForm
from werkzeug.security import generate_password_hash, check_password_hash
from wtforms.fields.simple import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

from utils.prediction import predict_body_shape

# /routes/user.py
user_bp = Blueprint('user', __name__)


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Register')


@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        hashed_password = generate_password_hash(password, method='scrypt')

        query = "INSERT INTO user (username, password) VALUES (?, ?)"
        g.db.execute(query, (username, hashed_password))
        g.db.commit()

        return redirect(url_for('user.login'))

    return render_template('register.html', form=form)


@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        query = "SELECT * FROM user WHERE username = ?"
        user = g.db.execute(query, (username,)).fetchone()

        if user and check_password_hash(user[2], password):
            session['user_id'] = user[0]
            session['username'] = user[1]
            return redirect(url_for('main.index'))

    return render_template('login.html', form=form)


@user_bp.route('/logout')
def logout():
    session.pop('user_id', None)
    session.pop('username', None)
    return redirect(url_for('main.index'))


@user_bp.route('/like_product', methods=['POST'])
def like_product():
    data = request.get_json()
    product_id = data.get('product_id')
    liked = data.get('liked')
    user_id = session.get('user_id')

    if not user_id:
        return jsonify({'success': False, 'message': 'User not logged in'})

    query_check = "SELECT * FROM user_likes WHERE user_id = ? AND item_id = ?"
    existing_like = g.db.execute(query_check, (user_id, product_id)).fetchone()

    if liked and not existing_like:
        query_insert = "INSERT INTO user_likes (user_id, item_id) VALUES (?, ?)"
        g.db.execute(query_insert, (user_id, product_id))
    elif not liked and existing_like:
        query_delete = "DELETE FROM user_likes WHERE user_id = ? AND item_id = ?"
        g.db.execute(query_delete, (user_id, product_id))

    g.db.commit()
    return jsonify({'success': True})


@user_bp.route('/save_preferences', methods=['POST'])
def save_preferences():
    user_id = session.get('user_id')
    if not user_id:
        return redirect(url_for('user.login'))
    save_user_preferences(user_id, request.form)
    return redirect(url_for('recommendations.recommend'))


@user_bp.route('/test_save_preferences', methods=['POST'])
def test_save_preferences():
    user_id = session.get('user_id')
    if not user_id:
        return redirect(url_for('user.login'))
    save_user_preferences(user_id, request.form)
    return redirect(url_for('recommendations.test_recommend'))


def save_user_preferences(user_id, request_form):
    body_shape = request_form.get('shape')
    gender = request_form.get('gender')
    skin_tone = request_form.get('skin_tone')
    chest = request_form.get('Chest')
    waist = request_form.get('Waist')
    high_hip = request_form.get('High')
    hip = request_form.get('Hip')

    valid_shapes = ['Rectangle', 'Triangle', 'Inverted Triangle', 'Hourglass', 'Top Hourglass', 'Bottom Hourglass', 'Spoon']
    if body_shape not in valid_shapes:
        if all([chest, waist, high_hip, hip]):
            body_shape = predict_body_shape(gender, chest, waist, high_hip, hip)
        else:
            body_shape = None

    query_check = "SELECT * FROM user_preferences WHERE user_id = ?"
    existing_preferences = g.db.execute(query_check, (user_id,)).fetchone()

    if existing_preferences:
        query_update = """
        UPDATE user_preferences
        SET body_shape = ?, gender = ?, skin_tone = ?, chest = ?, waist = ?, high_hip = ?, hip = ?
        WHERE user_id = ?
        """
        g.db.execute(query_update, (body_shape, gender, skin_tone, chest, waist, high_hip, hip, user_id))
    else:
        query_insert = """
        INSERT INTO user_preferences (user_id, body_shape, gender, skin_tone, chest, waist, high_hip, hip)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """
        g.db.execute(query_insert, (user_id, body_shape, gender, skin_tone, chest, waist, high_hip, hip))
    g.db.commit()


@user_bp.route('/save_rating', methods=['POST'])
def save_rating():
    try:
        data = request.json
        user_id = session.get('user_id')
        product_id = data.get('product_id')
        likert_scale = data.get('likert_scale')
        matching_slider = data.get('matching_slider')
        shape_slider = data.get('shape_slider')
        skin_tone_slider = data.get('skin_tone_slider')
        filtering = data.get('filtering')
        if not user_id:
            return jsonify({'success': False, 'message': 'User not logged in'}), 401
        query = """
            INSERT OR REPLACE INTO user_ratings
            (user_id, product_id, filtering, likert_scale, matching_slider, shape_slider, skin_tone_slider)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """
        g.db.execute(query,
                     (user_id, product_id, filtering, likert_scale, matching_slider, shape_slider, skin_tone_slider))
        g.db.commit()
        return jsonify({'success': True})
    except Exception as e:
        print(e)
        return jsonify({'success': False, 'message': str(e)}), 500


@user_bp.route('/get_rating', methods=['GET'])
def get_rating():
    user_id = request.args.get('user_id')
    product_id = request.args.get('product_id')
    filtering = request.args.get('filtering')
    query = """
        SELECT likert_scale, matching_slider, shape_slider, skin_tone_slider
        FROM user_ratings
        WHERE user_id = ? AND product_id = ? AND filtering = ?
    """
    rating = g.db.execute(query, (user_id, product_id, filtering)).fetchone()
    if rating:
        return jsonify({
            'success': True,
            'rating': {
                'likert_scale': rating[0],
                'matching_slider': rating[1],
                'shape_slider': rating[2],
                'skin_tone_slider': rating[3]
            }
        })
    else:
        return jsonify({'success': False})

my_project/Enhancing Personal Style/templates/login.html
<!--templates/login.html-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enhancing Personal Style</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/style/credentials.css') }}">
  </head>
  <body>
    <div class="container">
      <h1>Login</h1>
      <form method="POST" action="{{ url_for('user.login') }}">
        {{ form.csrf_token }}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
        <input type="submit" value="Login">
      </form>
    </div>
  </body>
</html>

my_project/Enhancing Personal Style/templates/recommendation.html
<!--templates/recommendation.html-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enhancing Personal Style</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/recommend.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='script/recommend.js') }}"></script>
</head>
<body>
    <div class="top-bar">
        <a href="{{ url_for('main.index') }}" class="home-icon">
            <img src="{{ url_for('static', filename='assets/home/home.svg') }}" alt="Home Icon">
        </a>
        <div class="dropdown">
            <button class="dropbtn">
                <img src="{{ url_for('static', filename='assets/user/user.svg') }}" alt="User Info Dropdown">
            </button>
            <div class="dropdown-content">
                <p>Body shape: {{ user_shape }}</p>
                <p>Gender: {{ user_gender }}</p>
                <p>Skin tone: {{ user_skin_tone }}</p>
            </div>
        </div>
    </div>
    <h1>Recommended Products</h1>
    {% for articleType, items in products.items() %}
        <div class="article-type">
            <h2>{{ articleType }}</h2>
            <div class="product-list">
                {% for product in items %}
                    <div class="product">
                        {% if product.recommended_by == 'collaborative_filtering' %}
                            <div class="cf-message">{{ product.liked_by_count }} user(s) also liked this</div>
                        {% endif %}
                        <h3>{{ product.product_display_name }}</h3>
                        <img src="{{ product.product_image_link }}" alt="Product Image" class="product-image">
                        <a href="{{ product.amazon_search_url }}" target="_blank" class="no-underline">
                            <button type="submit" class="amazon-btn">
                                <img src="{{ url_for('static', filename='assets/amazon/amazon.svg') }}" alt="Amazon Icon">
                                Search for Product
                            </button>
                        </a>
                        <form method="POST" action="{{ url_for('user.like_product') }}" class="like-form" data-product-id="{{ product.id }}">
                            {{ form.hidden_tag() }}
                            <input type="hidden" name="product_id" value="{{ product.id }}">
                            {% if product.id in liked_products %}
                                <button type="button" class="like-btn" title="You liked this item!">
                                    <img src="{{ url_for('static', filename='assets/like/like.svg') }}" alt="Unlike">
                                </button>
                            {% else %}
                                <button type="button" class="like-btn" title="You haven't liked this item!">
                                    <img src="{{ url_for('static', filename='assets/like/unlike.svg') }}" alt="Like">
                                </button>
                            {% endif %}
                        </form>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</body>
</html>

my_project/Enhancing Personal Style/templates/register.html
<!--templates/register.html-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enhancing Personal Style</title>
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='/style/credentials.css') }}">
  </head>
  <body>
    <div class="container">
      <h1>Register</h1>
      <form method="POST" action="{{ url_for('user.register') }}">
        {{ form.csrf_token }}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
        <input type="submit" value="Register">
      </form>
    </div>
  </body>
</html>

my_project/Enhancing Personal Style/templates/user_testing_recommendation.html
<!--templates/user_testing_recommendation.html-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="user-id" content="{{ user_id }}">
    <title>User Testing - Recommendations</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/test_recommend.css') }}">
    <style type="text/css">
        * {
            -webkit-user-select: text !important;
            -moz-user-select: text !important;
            -ms-user-select: text !important;
            user-select: text !important;
        }
    </style>
</head>
<body>
    <div class="top-bar">
        <a href="{{ url_for('test.test') }}" class="home-icon">
            <img src="{{ url_for('static', filename='assets/home/home.svg') }}" alt="Home Icon">
        </a>
        <div class="dropdown">
            <button class="dropbtn">
                <img src="{{ url_for('static', filename='assets/user/user.svg') }}" alt="User Info Dropdown">
            </button>
            <div class="dropdown-content">
                <p>Body shape: {{ user_shape }}</p>
                <p>Gender: {{ user_gender }}</p>
                <p>Skin tone: {{ user_skin_tone }}</p>
            </div>
        </div>
    </div>
    <div class="container">
        <h1>Recommended Products</h1>
        <div class="content-wrapper">
            <div id="product-container" class="product">
                <p id="loading-placeholder" style="text-align:center;">Loading recommendations...</p>
            </div>
            <div id="testing-form">
                <form id="rating-form">
                    <label for="likert-scale" class="form-label">How satisfied are you with this recommendation?</label>
                    <div class="scale">
                        <span class="scale-element">Extremely Dislike</span>
                        <input type="range" id="likert-scale" name="likert_scale" class="likert-scale" min="1" max="5" step="0.1" required>
                        <span class="scale-element">Extremely Like</span>
                    </div>
                    <br>
                    <label for="matching_slider" class="form-label">How closely does the product image relate to its description?</label>
                    <div class="scale">
                        <span class="scale-element">Extremely Unmatch</span>
                        <input type="range" id="matching_slider" name="matching_slider" class="matching-slider" min="1" max="5" step="0.1" required>
                        <span class="scale-element">Extremely Match</span>
                    </div>
                    <br>
                    <label for="shape-slider" class="form-label">How do you rate the product's compatibility for your body type?</label>
                    <div class="scale">
                        <span class="scale-element">Extremely Unsuitable</span>
                        <input type="range" id="shape-slider" name="shape_slider" class="shape-slider" min="1" max="5" step="0.1" required>
                        <span class="scale-element">Extremely Suitable</span>
                    </div>
                    <br>
                    <label for="skin-tone-slider" class="form-label">How do you rate the product's compatibility for your skin tone?</label>
                    <div class="scale">
                        <span class="scale-element">Extremely Unsuitable</span>
                        <input type="range" id="skin-tone-slider" name="skin_tone_slider" class="skin-tone-slider" min="1" max="5" step="0.1" required>
                        <span class="scale-element">Extremely Suitable</span>
                    </div>
                    <input type="hidden" id="product-id" name="product_id">
                    <div id="message-container" class="message-container"></div>
                    <div class="submit-button-container">
                        <button type="submit"><strong>Submit Rating</strong></button>
                    </div>
                </form>
            </div>
        </div>
        <div class="navigation-buttons">
            <button id="previous-product-btn" class="previous-product-btn"><strong>Previous Product</strong></button>
            <button id="next-product-btn" class="next-product-btn"><strong>Next Product</strong></button>
        </div>
    </div>
    <script type="text/javascript">
        const products = JSON.parse({{ products | tojson | safe }});
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='script/test_recommend.js') }}"></script>
</body>
</html>